<?php
$idioma["titulo_opcao_cadastar"] = "Cadastrar";
$idioma["titulo_opcao_editar"] = "Editar";
$idioma["form_erros"] = "Por favor corrija o(s) erro(s) abaixo: ";
$idioma["modificar_sucesso"] = "Fórmula modificada com sucesso.";
$idioma["legendadadosdados"] = "Dados da fórmula";
$idioma["form_nome"] = "Nome:";
$idioma["nome_vazio"] = "Informe o nome da fórmula.";
$idioma["nome_utilizado"] = "O nome informado já está sendo utilizado por outra fórmula.";
$idioma["form_ativo_painel"] = "Ativo no painel";
$idioma["ativo_vazio"] = "Você precisa informar se está ativo ou não.";
$idioma["form_ativo_ajuda"] = "Essa funcionalidade não remove do painel, somente oculta em relacionamentos com outras funcionalidades";
$idioma["form_formula"] = "Fórmula:";
$idioma["formula_vazio"] = "Informe a fórmula.";

$idioma["label_tipos_notas"] = 'Tipos de notas:';

$idioma["label_variaveis"] = "Variáveis";
$idioma["label_notas"] = "Variáveis de notas:";
$idioma["btn_1_nota_normal"] = "1ª normal";
$idioma["btn_2_nota_normal"] = "2ª normal";
$idioma["btn_1_nota_virtual"] = "1ª virtual";
$idioma["btn_2_nota_virtual"] = "2ª virtual";
$idioma["tooltip_1_nota_normal"] = "1ª nota normal";
$idioma["tooltip_2_nota_normal"] = "2ª nota normal";
$idioma["tooltip_1_nota_virtual"] = "1ª nota virtual";
$idioma["tooltip_2_nota_virtual"] = "2ª nota virtual";
$idioma["label_pesos"] = "Variáveis de pesos:";
$idioma["tooltip_1_peso_normal"] = "Peso da 1ª nota normal";
$idioma["tooltip_2_peso_normal"] = "Peso da 2ª nota normal";
$idioma["tooltip_1_peso_virtual"] = "Peso da 1ª nota virtual";
$idioma["tooltip_2_peso_virtual"] = "Peso da 2ª nota virtual";
$idioma["label_funcoes"] = "Variáveis de funções:";
$idioma["btn_maximo"] = "Máximo";
$idioma["btn_minimo"] = "Mínimo";
$idioma["btn_media"] = "Média";
$idioma["btn_maior_media"] = "Maior que Média";
$idioma["btn_arredondar"] = "Arredondar";
$idioma["btn_piso"] = "Piso";
$idioma["btn_teto"] = "Teto";
$idioma["btn_maior"] = "Maior nota";
$idioma["btn_limpar"] = "Limpar";
$idioma["tooltip_maximo"] = "Máximo<br />Ex.: >>(2,0;3,0) = 3,0";
$idioma["tooltip_minimo"] = "Mínimo<br />Ex.: <<(5,0;7,0) = 5,0";
$idioma["tooltip_media"] = "Média<br />Ex.: //(4,0;8,0) = 6,0";
$idioma["tooltip_maior_media"] = "Maior que a Média<br />Ex.: &&(4,0;[[MC]])";
$idioma["tooltip_arredondar"] = "Arredondar<br />Ex.: @(7,3) = 7,0";
$idioma["tooltip_piso"] = "Piso<br />Ex.: _(6,4) = 6,0";
$idioma["tooltip_teto"] = "Teto<br />Ex.: #(8,7) = 9,0";
$idioma["tooltip_maior"] = "Será considerada somente a maior nota";
