<?php

if ($url[4] == 'editar') {
    $disabled = 'disabled';
}

$config['formulario'] = array(
    array(
        'fieldsetid' => 'dadosdoobjeto',
        'legendaidioma' => 'legendadadosdados',
        'campos' => array(
            array(
                'id' => 'form_razao_social',
                'nome' => 'razao_social',
                'nomeidioma' => 'form_razao_social',
                'tipo' => 'input',
                'valor' => 'razao_social',
                'validacao' => array('required' => 'razao_social_vazio'),
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_nome_fantasia',
                'nome' => 'nome_fantasia',
                'nomeidioma' => 'form_nome_fantasia',
                'tipo' => 'input',
                'valor' => 'nome_fantasia',
                'validacao' => array('required' => 'nome_fantasia_vazio'),
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_tipo',
                'nome' => 'documento_tipo',
                'nomeidioma' => 'form_tipo',
                'botao_hide' => true,
                'iddivs' => array('documento','documento_cnpj'),
                'tipo' => 'select',
                'iddiv' => 'documento',
                'iddiv2' => 'documento_cnpj',
                'array' => 'tipo_documento',
                'class' => 'span2',
                'valor' => 'documento_tipo',
                'banco' => true,
                'banco_string' => true,
                'evento' => $disabled,
            ),
            array(
                'id' => 'form_documento',
                'nome' => 'documento',
                'nomeidioma' => 'form_cpf',
                'tipo' => 'input',
                'valor' => 'documento',
                'class' => 'span3',
                'ajudaidioma' => 'form_cpf_ajuda',
                'evento' => "maxlength='14'" . $disabled,
                'banco' => true,
                'banco_php' => 'return str_replace(array(".", "-","/"),"","%s")',
                "mascara" => "999.999.999-99",
                'banco_string' => true,
                'input_hidden' => true,
            ),
            array(
                'id' => 'form_documento_cnpj',
                'nome' => 'documento_cnpj',
                'nomeidioma' => 'form_cnpj',
                'tipo' => 'input',
                'valor' => 'documento',
                'class' => 'span3',
                'ajudaidioma' => 'form_cnpj_ajuda',
                'evento' => "maxlength='18'" . $disabled,
                'banco' => true,
                'banco_php' => 'return str_replace(array(".", "-", "/"),"","%s")',
                "mascara" => "99.999.999/9999-99",
                'banco_string' => true,
                'input_hidden' => true,
            ),
            array(
                'id' => 'idsindicato',
                'nome' => 'idsindicato',
                'nomeidioma' => 'form_sindicato',
                'tipo' => 'select',
                'sql' => "select idsindicato, nome_abreviado as nome FROM sindicatos WHERE ativo = 'S' AND ativo_painel = 'S' ORDER BY nome ",
                'sql_valor' => 'idsindicato',
                'sql_label' => 'nome',
                'valor' => 'idsindicato',
                'validacao' => array('required' => 'sindicato_vazio'),
                'referencia_label' => 'cadastro_sindicato',
                'referencia_link' => '/gestor/cadastros/sindicatos',
                'banco' => true
            ),
            array(
                'id' => 'form_slug',
                'nome' => 'slug',
                'nomeidioma' => 'form_slug',
                'tipo' => 'select',
                'sql' => "SELECT idusuario, nome FROM usuarios_adm WHERE idperfil IN (9, 17) ORDER BY nome",
                'sql_valor' => 'idusuario',
                'sql_label' => 'nome',
                'valor' => 'idusuario',
                'validacao' => array('required' => 'slug_vazio'),
//                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='30'"
            ),
            array(
                'id' => 'form_inscricao_estadual',
                'nome' => 'inscricao_estadual',
                'nomeidioma' => 'form_inscricao_estadual',
                'tipo' => 'input',
                'valor' => 'inscricao_estadual',
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_inscricao_municipal',
                'nome' => 'inscricao_municipal',
                'nomeidioma' => 'form_inscricao_municipal',
                'tipo' => 'input',
                'valor' => 'inscricao_municipal',
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
//            array(
//                'id' => 'form_fax',
//                'nome' => 'fax',
//                'nomeidioma' => 'form_fax',
//                'tipo' => 'input',
//                'valor' => 'fax',
//                'class' => 'span3',
//                'mascara' => '(99) 9999-9999',
//                'banco' => true,
//                'banco_string' => true
//            ),
            array(
                'id' => 'form_email',
                'nome' => 'email',
                'nomeidioma' => 'form_email',
                'tipo' => 'input',
                'valor' => 'email',
                'class' => 'span5',
                'legenda' => '@',
                'validacao' => array('required' => 'email_vazio', 'valid_email' => 'email_invalido'),
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_site',
                'nome' => 'site',
                'nomeidioma' => 'form_site',
                'tipo' => 'input',
                'evento' => "maxlength='50'",
                'valor' => 'site',
                'class' => 'span2',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_telefone',
                'nome' => 'telefone',
                'nomeidioma' => 'form_telefone',
                'tipo' => 'input',
                'valor' => 'telefone',
                'class' => 'span3',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_cep',
                'nome' => 'cep',
                'nomeidioma' => 'form_cep',
                'tipo' => 'input',
                'valor' => 'cep',
                'class' => 'span2',
                'mascara' => '99999-999',
                'banco' => true,
                'banco_php' => 'return str_replace(array("-", ""),"","%s")',
                'banco_string' => true
            ),
            array(
                'id' => 'idlogradouro',
                'nome' => 'idlogradouro',
                'nomeidioma' => 'form_logradouro',
                'tipo' => 'select',
                'sql' => "SELECT idlogradouro, nome FROM logradouros WHERE ativo = 'S' AND ativo_painel = 'S' ORDER BY nome ",
                'sql_valor' => 'idlogradouro',
                'sql_label' => 'nome',
                'valor' => 'idlogradouro',
                'banco' => true
            ),
            array(
                'id' => 'form_endereco',
                'nome' => 'endereco',
                'nomeidioma' => 'form_endereco',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'endereco',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_bairro',
                'nome' => 'bairro',
                'nomeidioma' => 'form_bairro',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'bairro',
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_numero',
                'nome' => 'numero',
                'nomeidioma' => 'form_numero',
                'ajudaidioma' => 'form_numero_ajuda',
                'tipo' => 'input',
                'evento' => "maxlength='10'",
                'valor' => 'numero',
                'class' => 'span2',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_complemento',
                'nome' => 'complemento',
                'nomeidioma' => 'form_complemento',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'complemento',
                'class' => 'span4',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'idestado',
                'nome' => 'idestado',
                'nomeidioma' => 'form_idestado',
                'tipo' => 'select',
                'sql' => 'SELECT idestado, nome FROM estados ORDER BY nome',
                'sql_valor' => 'idestado',
                'sql_label' => 'nome',
                'valor' => 'idestado',
                'validacao' => array('required' => 'estado_vazio'),
                'banco' => true
            ),
            array(
                'id' => 'idcidade',
                'nome' => 'idcidade',
                'nomeidioma' => 'form_idcidade',
                'json' => true,
                'json_idpai' => 'idestado',
                'json_url' => '/' . $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'] . '/ajax_cidades/',
                'json_input_pai_vazio' => 'form_selecione_estado',
                'json_input_vazio' => 'form_selecione_cidade',
                'json_campo_exibir' => 'nome',
                'tipo' => 'select',
                'valor' => 'idcidade',
                'validacao' => array('required' => 'cidade_vazio'),
                'banco' => true
            ),
            array(
                'id' => 'form_ativo_painel',
                'nome' => 'ativo_painel',
                'nomeidioma' => 'form_ativo_painel',
                'tipo' => 'select',
                'array' => 'ativo',
                'class' => 'span2',
                'valor' => 'ativo_painel',
                'validacao' => array('required' => 'ativo_vazio'),
                'ajudaidioma' => 'form_ativo_ajuda',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_matriculas_por_mes',
                'nome' => 'matriculas_por_mes',
                'nomeidioma' => 'form_matriculas_por_mes',
                'tipo' => 'input',
                'valor' => 'matriculas_por_mes',
                'class' => 'span2',
                'banco' => true,
                'numerico' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_ciretran',
                'nome' => 'ciretran',
                'nomeidioma' => 'form_ciretran',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'ciretran',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_ciretran_numero',
                'nome' => 'ciretran_numero',
                'nomeidioma' => 'form_ciretran_numero',
                'tipo' => 'input',
                'evento' => "maxlength='10'",
                'valor' => 'ciretran_numero',
                'class' => 'span2',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_ciretran_cidade',
                'nome' => 'ciretran_cidade',
                'nomeidioma' => 'form_ciretran_cidade',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'ciretran_cidade',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_informacoes',
                'nome' => 'informacoes',
                'nomeidioma' => 'form_informacoes',
                'tipo' => 'text',
                'valor' => 'informacoes',
                'class' => 'span4',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_receber_email',
                'nome' => 'receber_email',
                'nomeidioma' => 'form_receber_email',
                'validacao' => array('required' => "receber_email_vazio"),
                'tipo' => 'select',
                'array' => 'sim_nao',
                'class' => 'span2',
                'valor' => 'receber_email',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_exibir_campos',
                'nome' => 'exibir_campos',
                'nomeidioma' => 'form_exibir_campos',
                'tipo' => 'select',
                'array' => 'sim_nao',
                'class' => 'span2',
                'valor' => 'exibir_campos',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_criar_matricula',
                'nome' => 'criar_matricula',
                'nomeidioma' => 'form_criar_matricula',
                'tipo' => 'select',
                'ajudaidioma' => 'form_ajuda_criar_matricula',
                'array' => 'sim_nao',
                'class' => 'span2',
                'valor' => 'criar_matricula',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_modificar_matricula',
                'nome' => 'modificar_matricula',
                'nomeidioma' => 'form_modificar_matricula',
                'tipo' => 'select',
                'ajudaidioma' => 'form_ajuda_modificar_matricula',
                'array' => 'sim_nao',
                'class' => 'span2',
                'valor' => 'modificar_matricula',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_bloquear_mudanca_turma',
                'nome' => 'bloquear_mudanca_turma',
                'nomeidioma' => 'form_bloquear_mudanca_turma',
                'tipo' => 'select',
                'ajudaidioma' => 'form_ajuda_bloquear_mudanca_turma',
                'array' => 'sim_nao',
                'class' => 'span2',
                'valor' => 'bloquear_mudanca_turma',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_parceiro',
                'nome' => 'parceiro',
                'nomeidioma' => 'form_parceiro',
                'tipo' => 'select',
                'array' => 'sim_nao',
                'class' => 'span2',
                'valor' => 'parceiro',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_periodo_fatura',
                'nome' => 'periodo_faturas',
                'nomeidioma' => 'form_periodo_fatura',
                'tipo' => 'select',
                'array' => 'periodo_fatura',
                'class' => 'span2',
                'valor' => 'periodo_faturas',
                'sem_primeira_linha' => true,
                'banco' => true,
                'banco_string' => true
            ),
        )
    ),
    array(
        'fieldsetid' => 'foto',
        'legendaidioma' => 'legenda_foto',
        'campos' => array(
            array(
                'id' => 'form_foto',
                'nome' => 'avatar',
                'nomeidioma' => 'form_foto',
                'arquivoidioma' => 'arquivo_enviado',
                'arquivoexcluir' => 'arquivo_excluir',
                'tipo' => 'file',
                'extensoes' => 'jpg|jpeg|gif|png|bmp',
                'ajudaidioma' => 'form_foto_ajuda',
                'validacao' => array('formato_arquivo' => 'arquivo_invalido'),
                'class' => 'span6',
                'pasta' => 'escolas_avatar',
                'download' => true,
                'download_caminho' => $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'],
                'excluir' => true,
                'banco' => true,
                'banco_campo' => 'avatar',
                'ignorarsevazio' => true
            ),
        )
    ),
    array(
        'fieldsetid' => 'dadosdeacesso',
        'legendaidioma' => 'legendadadosdeacesso',
        'campos' => array(
            array(
                'id' => 'form_senha',
                'nome' => 'senha',
                'nomeidioma' => 'form_senha',
                'tipo' => 'input',
                'senha' => true,
                'ajudaidioma' => 'form_senha_ajuda',
                'class' => 'span3 verificaSenha',
                'validacao' => array('length>=8' => 'minimo_senha', 'length<=30' => 'maximo_senha'),
                'legenda' => '#',
                'ignorarsevazio' => true,
                'banco' => true,
                'banco_php' => 'return senhaSegura("%s","' . $config['chaveLogin'] . '")',
                'banco_string' => true,
                'evento' => "maxlength='30'"
            ),
            array(
                'id' => 'form_confirma',
                'nome' => 'confirma',
                'nomeidioma' => 'form_confirma',
                'tipo' => 'input',
                'senha' => true,
                'ajudaidioma' => 'form_confirma_ajuda',
                'validacao' => array('same_as,senha' => 'confirmacao_invalida'),
                'class' => 'span4',
                'evento' => "maxlength='30'"
            )
        )
    ),
    array(
        'fieldsetid' => 'dados_gerente',
        'legendaidioma' => 'legenda_dados_gerente',
        'campos' => array(
            array(
                'id' => 'form_gerente_nome',
                'nome' => 'gerente_nome',
                'nomeidioma' => 'form_gerente_nome',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'gerente_nome',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_gerente_cpf',
                'nome' => 'gerente_cpf',
                'nomeidioma' => 'form_gerente_cpf',
                'tipo' => 'input',
                'valor' => 'gerente_cpf',
                'class' => 'span2',
                'evento' => "maxlength='14'",
                "validacao" => array("valida_cpf" => "gerente_cpf_invalido"),
                "mascara" => "999.999.999-99",
                'banco' => true,
                'banco_php' => 'return str_replace(array(".", "-","/"),"","%s")',
                'banco_string' => true
            ),
            array(
                'id' => 'form_gerente_data_nasc',
                'nome' => 'gerente_data_nasc',
                'nomeidioma' => 'form_gerente_data_nasc',
                'tipo' => 'input',
                'valor' => 'gerente_data_nasc',
                'valor_php' => '
                    if ($dados["gerente_data_nasc"] && $dados["gerente_data_nasc"] != "0000-00-00") {
                        return formataData("%s", "br", 0);
                    }',
                'class' => 'span2',
                'mascara' => '99/99/9999',
                'banco' => true,
                'banco_php' => 'return formataData("%s", "en", 0)',
                'banco_string' => true
            ),
            array(
                'id' => 'form_gerente_email',
                'nome' => 'gerente_email',
                'nomeidioma' => 'form_gerente_email',
                'tipo' => 'input',
                'valor' => 'gerente_email',
                'validacao' => array('valid_email' => 'gerente_email_invalido'),
                'class' => 'span5',
                'legenda' => '@',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_gerente_telefone',
                'nome' => 'gerente_telefone',
                'nomeidioma' => 'form_gerente_telefone',
                'tipo' => 'input',
                'valor' => 'gerente_telefone',
                'class' => 'span2',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_gerente_celular',
                'nome' => 'gerente_celular',
                'nomeidioma' => 'form_gerente_celular',
                'tipo' => 'input',
                'valor' => 'gerente_celular',
                'class' => 'span2',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_gerente_profissao',
                'nome' => 'gerente_profissao',
                'nomeidioma' => 'form_gerente_profissao',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'gerente_profissao',
                'class' => 'span3',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_gerente_cep',
                'nome' => 'gerente_cep',
                'nomeidioma' => 'form_gerente_cep',
                'tipo' => 'input',
                'valor' => 'gerente_cep',
                'class' => 'span2',
                'mascara' => '99999-999',
                'banco' => true,
                'banco_php' => 'return str_replace(array("-", ""),"","%s")',
                'banco_string' => true
            ),
            array(
                'id' => 'form_gerente_idlogradouro',
                'nome' => 'gerente_idlogradouro',
                'nomeidioma' => 'form_gerente_idlogradouro',
                'tipo' => 'select',
                'sql' => "SELECT idlogradouro, nome FROM logradouros WHERE ativo = 'S' AND ativo_painel = 'S' ORDER BY nome ",
                'sql_valor' => 'idlogradouro',
                'sql_label' => 'nome',
                'valor' => 'gerente_idlogradouro',
                'banco' => true
            ),
            array(
                'id' => 'form_gerente_endereco',
                'nome' => 'gerente_endereco',
                'nomeidioma' => 'form_gerente_endereco',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'gerente_endereco',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_gerente_bairro',
                'nome' => 'gerente_bairro',
                'nomeidioma' => 'form_gerente_bairro',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'gerente_bairro',
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_gerente_numero',
                'nome' => 'gerente_numero',
                'nomeidioma' => 'form_gerente_numero',
                'ajudaidioma' => 'form_gerente_numero_ajuda',
                'tipo' => 'input',
                'evento' => "maxlength='10'",
                'valor' => 'gerente_numero',
                'class' => 'span2',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_gerente_complemento',
                'nome' => 'gerente_complemento',
                'nomeidioma' => 'form_gerente_complemento',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'gerente_complemento',
                'class' => 'span4',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'gerente_idestado',
                'nome' => 'gerente_idestado',
                'nomeidioma' => 'form_gerente_idestado',
                'tipo' => 'select',
                'sql' => 'SELECT idestado, nome FROM estados ORDER BY nome',
                'sql_valor' => 'idestado',
                'sql_label' => 'nome',
                'valor' => 'gerente_idestado',
                'banco' => true
            ),
            array(
                'id' => 'gerente_idcidade',
                'nome' => 'gerente_idcidade',
                'nomeidioma' => 'form_gerente_idcidade',
                'json' => true,
                'json_idpai' => 'gerente_idestado',
                'json_url' => '/' . $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'] . '/ajax_cidades/',
                'json_input_pai_vazio' => 'form_selecione_estado',
                'json_input_vazio' => 'form_selecione_cidade',
                'json_campo_exibir' => 'nome',
                'tipo' => 'select',
                'valor' => 'gerente_idcidade',
                'banco' => true
            ),
            array(
                'id' => 'form_gerente_assinatura',
                'nome' => 'gerente_assinatura',
                'nomeidioma' => 'form_gerente_assinatura',
                'arquivoidioma' => 'arquivo_enviado',
                'arquivoexcluir' => 'arquivo_excluir',
                'tipo' => 'file',
                'extensoes' => 'jpg|jpeg|gif|png|bmp',
                'ajudaidioma' => 'form_gerente_assinatura_ajuda',
                'validacao' => array('formato_arquivo' => 'gerente_assinatura_invalido'),
                'class' => 'span6',
                'pasta' => 'escolas_gerente_assinatura',
                'download' => true,
                'download_caminho' => $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'],
                'excluir' => true,
                'banco' => true,
                'banco_campo' => 'gerente_assinatura',
                'ignorarsevazio' => true
            )
        )
    ),
    array(
        'fieldsetid' => 'dados_responsavel_legal',
        'legendaidioma' => 'legenda_dados_responsavel_legal',
        'campos' => array(
            array(
                'id' => 'form_responsavel_legal_nome',
                'nome' => 'responsavel_legal_nome',
                'nomeidioma' => 'form_responsavel_legal_nome',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'responsavel_legal_nome',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_responsavel_legal_cpf',
                'nome' => 'responsavel_legal_cpf',
                'nomeidioma' => 'form_responsavel_legal_cpf',
                'tipo' => 'input',
                'valor' => 'responsavel_legal_cpf',
                'class' => 'span2',
                'evento' => "maxlength='14'",
                "validacao" => array("valida_cpf" => "responsavel_legal_cpf_invalido"),
                "mascara" => "999.999.999-99",
                'banco' => true,
                'banco_php' => 'return str_replace(array(".", "-","/"),"","%s")',
                'banco_string' => true
            ),
            array(
                'id' => 'form_responsavel_legal_data_nasc',
                'nome' => 'responsavel_legal_data_nasc',
                'nomeidioma' => 'form_responsavel_legal_data_nasc',
                'tipo' => 'input',
                'valor' => 'responsavel_legal_data_nasc',
                'valor_php' => '
                    if ($dados["responsavel_legal_data_nasc"] && $dados["responsavel_legal_data_nasc"] != "0000-00-00") {
                        return formataData("%s", "br", 0);
                    }',
                'class' => 'span2',
                'mascara' => '99/99/9999',
                'banco' => true,
                'banco_php' => 'return formataData("%s", "en", 0)',
                'banco_string' => true
            ),
            array(
                'id' => 'form_responsavel_legal_email',
                'nome' => 'responsavel_legal_email',
                'nomeidioma' => 'form_responsavel_legal_email',
                'tipo' => 'input',
                'valor' => 'responsavel_legal_email',
                'validacao' => array('valid_email' => 'responsavel_legal_email_invalido'),
                'class' => 'span5',
                'legenda' => '@',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_responsavel_legal_telefone',
                'nome' => 'responsavel_legal_telefone',
                'nomeidioma' => 'form_responsavel_legal_telefone',
                'tipo' => 'input',
                'valor' => 'responsavel_legal_telefone',
                'class' => 'span2',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_responsavel_legal_celular',
                'nome' => 'responsavel_legal_celular',
                'nomeidioma' => 'form_responsavel_legal_celular',
                'tipo' => 'input',
                'valor' => 'responsavel_legal_celular',
                'class' => 'span2',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_responsavel_legal_profissao',
                'nome' => 'responsavel_legal_profissao',
                'nomeidioma' => 'form_responsavel_legal_profissao',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'responsavel_legal_profissao',
                'class' => 'span3',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_responsavel_legal_cep',
                'nome' => 'responsavel_legal_cep',
                'nomeidioma' => 'form_responsavel_legal_cep',
                'tipo' => 'input',
                'valor' => 'responsavel_legal_cep',
                'class' => 'span2',
                'mascara' => '99999-999',
                'banco' => true,
                'banco_php' => 'return str_replace(array("-", ""),"","%s")',
                'banco_string' => true
            ),
            array(
                'id' => 'form_responsavel_legal_idlogradouro',
                'nome' => 'responsavel_legal_idlogradouro',
                'nomeidioma' => 'form_responsavel_legal_idlogradouro',
                'tipo' => 'select',
                'sql' => "SELECT idlogradouro, nome FROM logradouros WHERE ativo = 'S' AND ativo_painel = 'S' ORDER BY nome ",
                'sql_valor' => 'idlogradouro',
                'sql_label' => 'nome',
                'valor' => 'responsavel_legal_idlogradouro',
                'banco' => true
            ),
            array(
                'id' => 'form_responsavel_legal_endereco',
                'nome' => 'responsavel_legal_endereco',
                'nomeidioma' => 'form_responsavel_legal_endereco',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'responsavel_legal_endereco',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_responsavel_legal_bairro',
                'nome' => 'responsavel_legal_bairro',
                'nomeidioma' => 'form_responsavel_legal_bairro',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'responsavel_legal_bairro',
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_responsavel_legal_numero',
                'nome' => 'responsavel_legal_numero',
                'nomeidioma' => 'form_responsavel_legal_numero',
                'ajudaidioma' => 'form_responsavel_legal_numero_ajuda',
                'tipo' => 'input',
                'evento' => "maxlength='10'",
                'valor' => 'responsavel_legal_numero',
                'class' => 'span2',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_responsavel_legal_complemento',
                'nome' => 'responsavel_legal_complemento',
                'nomeidioma' => 'form_responsavel_legal_complemento',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'responsavel_legal_complemento',
                'class' => 'span4',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'responsavel_legal_idestado',
                'nome' => 'responsavel_legal_idestado',
                'nomeidioma' => 'form_responsavel_legal_idestado',
                'tipo' => 'select',
                'sql' => 'SELECT idestado, nome FROM estados ORDER BY nome',
                'sql_valor' => 'idestado',
                'sql_label' => 'nome',
                'valor' => 'responsavel_legal_idestado',
                'banco' => true
            ),
            array(
                'id' => 'responsavel_legal_idcidade',
                'nome' => 'responsavel_legal_idcidade',
                'nomeidioma' => 'form_responsavel_legal_idcidade',
                'json' => true,
                'json_idpai' => 'responsavel_legal_idestado',
                'json_url' => '/' . $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'] . '/ajax_cidades/',
                'json_input_pai_vazio' => 'form_selecione_estado',
                'json_input_vazio' => 'form_selecione_cidade',
                'json_campo_exibir' => 'nome',
                'tipo' => 'select',
                'valor' => 'responsavel_legal_idcidade',
                'banco' => true
            ),
            array(
                'id' => 'form_responsavel_legal_assinatura',
                'nome' => 'responsavel_legal_assinatura',
                'nomeidioma' => 'form_responsavel_legal_assinatura',
                'arquivoidioma' => 'arquivo_enviado',
                'arquivoexcluir' => 'arquivo_excluir',
                'tipo' => 'file',
                'extensoes' => 'jpg|jpeg|gif|png|bmp',
                'ajudaidioma' => 'form_responsavel_legal_assinatura_ajuda',
                'validacao' => array('formato_arquivo' => 'responsavel_legal_assinatura_invalido'),
                'class' => 'span6',
                'pasta' => 'escolas_responsavel_legal_assinatura',
                'download' => true,
                'download_caminho' => $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'],
                'excluir' => true,
                'banco' => true,
                'banco_campo' => 'responsavel_legal_assinatura',
                'ignorarsevazio' => true
            )
        )
    ),
    array(
        'fieldsetid' => 'dados_diretor_ensino',
        'legendaidioma' => 'legenda_dados_diretor_ensino',
        'campos' => array(
            array(
                'id' => 'form_diretor_ensino_nome',
                'nome' => 'diretor_ensino_nome',
                'nomeidioma' => 'form_diretor_ensino_nome',
                'tipo' => 'input',
                'evento' => "maxlength='100'",
                'valor' => 'diretor_ensino_nome',
                'class' => 'span6',
                'banco' => true,
                'banco_string' => true,
            ),
            array(
                'id' => 'form_diretor_ensino_cpf',
                'nome' => 'diretor_ensino_cpf',
                'nomeidioma' => 'form_diretor_ensino_cpf',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_cpf',
                'class' => 'span2',
                'evento' => "maxlength='14'",
                "validacao" => array("valida_cpf" => "diretor_ensino_cpf_invalido"),
                "mascara" => "999.999.999-99",
                'banco' => true,
                'banco_php' => 'return str_replace(array(".", "-","/"),"","%s")',
                'banco_string' => true
            ),
            array(
                'id' => 'form_diretor_ensino_data_nasc',
                'nome' => 'diretor_ensino_data_nasc',
                'nomeidioma' => 'form_diretor_ensino_data_nasc',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_data_nasc',
                'valor_php' => '
                    if ($dados["diretor_ensino_data_nasc"] && $dados["diretor_ensino_data_nasc"] != "0000-00-00") {
                        return formataData("%s", "br", 0);
                    }',
                'class' => 'span2',
                'mascara' => '99/99/9999',
                'banco' => true,
                'banco_php' => 'return formataData("%s", "en", 0)',
                'banco_string' => true
            ),
            array(
                'id' => 'form_diretor_ensino_email',
                'nome' => 'diretor_ensino_email',
                'nomeidioma' => 'form_diretor_ensino_email',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_email',
                'validacao' => array('valid_email' => 'diretor_ensino_email_invalido'),
                'class' => 'span5',
                'legenda' => '@',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_diretor_ensino_telefone',
                'nome' => 'diretor_ensino_telefone',
                'nomeidioma' => 'form_diretor_ensino_telefone',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_telefone',
                'class' => 'span2',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_diretor_ensino_celular',
                'nome' => 'diretor_ensino_celular',
                'nomeidioma' => 'form_diretor_ensino_celular',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_celular',
                'class' => 'span2',
                'mascara' => '(99) 9999-9999',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_diretor_ensino_profissao',
                'nome' => 'diretor_ensino_profissao',
                'nomeidioma' => 'form_diretor_ensino_profissao',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_profissao',
                'class' => 'span3',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_diretor_ensino_skype',
                'nome' => 'diretor_ensino_skype',
                'nomeidioma' => 'form_diretor_ensino_skype',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_skype',
                'class' => 'span3',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_diretor_ensino_portaria',
                'nome' => 'diretor_ensino_portaria',
                'nomeidioma' => 'form_diretor_ensino_portaria',
                'tipo' => 'input',
                'valor' => 'diretor_ensino_portaria',
                'class' => 'span3',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'"
            ),
            array(
                'id' => 'form_diretor_ensino_assinatura',
                'nome' => 'diretor_ensino_assinatura',
                'nomeidioma' => 'form_diretor_ensino_assinatura',
                'arquivoidioma' => 'arquivo_enviado',
                'arquivoexcluir' => 'arquivo_excluir',
                'tipo' => 'file',
                'extensoes' => 'jpg|jpeg|gif|png|bmp',
                'ajudaidioma' => 'form_diretor_ensino_assinatura_ajuda',
                'validacao' => array('formato_arquivo' => 'diretor_ensino_assinatura_invalido'),
                'class' => 'span6',
                'pasta' => 'escolas_diretor_ensino_assinatura',
                'download' => true,
                'download_caminho' => $url['0'] . '/' . $url['1'] . '/' . $url['2'] . '/' . $url['3'],
                'excluir' => true,
                'banco' => true,
                'banco_campo' => 'diretor_ensino_assinatura',
                'ignorarsevazio' => true
            )
        )
    ),
    array(
        'fieldsetid' => 'dados_fastconnect',
        'legendaidioma' => 'legenda_dados_fastconnect',
        'campos' => array(
            array(
                'id' => 'form_fastconnect',
                'nome' => 'fastconnect',
                'nomeidioma' => 'form_fastconnect',
                'ajudaidioma' => 'form_fastconnect_ajuda',
                'tipo' => 'select',
                'valor' => 'fastconnect',
                'array' => 'sim_nao',
                'validacao' => array('required' => 'fastconnect_vazio'),
                'class' => 'span1',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'form_fastconnect_client_code',
                'nome' => 'fastconnect_client_code',
                'nomeidioma' => 'form_fastconnect_client_code',
                'tipo' => 'input',
                'valor' => 'fastconnect_client_code',
                'validacao' => array('required' => 'fastconnect_client_code_vazio'),
                'class' => 'span5',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='100'",
                'input_hidden' => true
            ),
            array(
                'id' => 'form_fastconnect_client_key',
                'nome' => 'fastconnect_client_key',
                'nomeidioma' => 'form_fastconnect_client_key',
                'tipo' => 'input',
                'valor' => 'fastconnect_client_key',
                'validacao' => array('required' => 'fastconnect_client_key_vazio'),
                'class' => 'span4',
                'banco' => true,
                'banco_string' => true,
                'evento' => "maxlength='32'",
                'input_hidden' => true
            )
        )
    ),
    array(
        'fieldsetid' => 'dados_detran',
        'legendaidioma' => 'legenda_dados_detran',
        'campos' => array(
            array(
                'id' => 'form_detran_codigo',
                'nome' => 'detran_codigo',
                'nomeidioma' => 'form_detran_codigo',
                'tipo' => 'input',
                'valor' => 'detran_codigo',
                "validacao" => array("length>=3" => "minimo_detran_codigo"),
                'class' => 'span2',
                'banco' => true,
                'banco_string' => true,
                'evento' => 'maxlength="8"',
                'input_hidden' => true
            )
        )
    )
);

$config['formulario_valores_curso'] = array(
    array(
        'fieldsetid' => 'dadosdoobjeto',
        'legendaidioma' => 'legendadadosdados',
        'campos' => array(
            array(
                'id' => 'disponivel_cfc',
                'nome' => 'disponivel_cfc',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'idcfc',
                'nome' => 'idcfc',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'idcurso',
                'nome' => 'idcurso',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
/*            array(
                'id' => 'avista',
                'nome' => 'avista',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true,
                'decimal' => true
            ),
            array(
                'id' => 'aprazo',
                'nome' => 'aprazo',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true,
                'decimal' => true
            ),*/
            array(
                'id' => 'parcelas',
                'nome' => 'parcelas',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'quantidade_matriculas',
                'nome' => 'quantidade_matriculas',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'valor_por_matricula',
                'nome' => 'valor_por_matricula',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true,
                'decimal' => true
            ),
            array(
                'id' => 'quantidade_matriculas_2',
                'nome' => 'quantidade_matriculas_2',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'valor_por_matricula_2',
                'nome' => 'valor_por_matricula_2',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true,
                'decimal' => true
            ),
            array(
                'id' => 'valor_excedente',
                'nome' => 'valor_excedente',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true,
                'decimal' => true
            ),
            array(
                'id' => 'quantidade_faturas_ciclo',
                'nome' => 'quantidade_faturas_ciclo',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
            array(
                'id' => 'qtd_parcelas',
                'nome' => 'qtd_parcelas',
                'tipo' => 'input',
                'banco' => true,
                'banco_string' => true
            ),
        ),
    ),
);
