<?
$idioma["form_erros"] = "Por favor corrija o(s) erro(s) abaixo: "; 
$idioma["titulo_opcao"] = "Associar Imagem";
$idioma["sair_edicao"] = "Sair da pesquisa";
$idioma["texto_explicativo"] = "Aqui você pode associar imagens à declaração.";
$idioma["confirmacao"] = "Confirmação:";
$idioma["nota"] = "<strong>Obs:</strong> Todas as ações do painel são monitoradas.";
$idioma["salvar"] = "Salvar";
$idioma["cancelar"] = "Cancelar";
$idioma['anexar_arquivo'] = "Anexar imagens:";
$idioma['outro_arquivo'] = "Anexar outra imagem";
$idioma['arquivo_invalido'] = "Formato de arquivo não permitido";
$idioma["imagem_sucesso"] = "Imagens(is) enviada(s) com sucesso.";
$idioma["listagem_id"] = "ID";
$idioma["listagem_nome"] = "Nome";
$idioma["listagem_tamanho"] = "Tamanho";
$idioma["listagem_opcoes"] = "Opções";
$idioma["btn_remover_permissao_excluir"] = "Sem permissão para remover.";
$idioma["confirmar_remocao"] = "Deseja realmente remover esta imagem?";
$idioma["remover_imagem_sucesso"] = "Imagem removido com sucesso.";
$idioma["btn_remover"] = "Remover imagem";
$idioma["btn_download"] = "Baixar imagem";
$idioma["btn_visualizar"] = "Visualizar imagem";
$idioma["visualizar"] = "Visualizar";
$idioma["baixar"] = "Baixar";
$idioma["sem_arquivos"] = "Obrigatório enviar ao menos 1 (um) arquivo."; 
$idioma["form_associar"] = "Selecione a(s) imagem(s) e clique em Salvar para associar à declaração.";
$idioma["salvar_permissao"] = "Sem permissão para cadastrar imagens.";
?>