<?php
$idioma["funcionalidade"] = "Ofertas";
$idioma["visualizar"] = "Listar ofertas";
$idioma["cadastrar_modificar"] = "Cadastrar e modificar ofertas";
$idioma["remover"] = "Remover ofertas";
$idioma["visualizar_cursos"] = "Visualizar cursos";
$idioma["associar_cursos"] = "Associar cursos";
$idioma["remover_cursos"] = "Remover cursos";
$idioma["visualizar_escolas"] = "Visualizar CFCs";
$idioma["associar_escolas"] = "Associar CFCs";
$idioma["remover_escolas"] = "Remover CFCs";
$idioma["visualizar_turmas"] = "Visualizar turmas";
$idioma["associar_turmas"] = "Associar turmas";
$idioma["remover_turmas"] = "Remover turmas";
$idioma["cursos_escolas"] = "Cursos x CFCs";
$idioma['cursos_sindicatos'] = 'Cursos x Estados';
$idioma["curriculos_avas"] = "Currículos x AVAS";
$idioma["clonar"] = "Clonar oferta";
$idioma["campos_prova_presencial"] = "Alterar regras/informações de provas presenciais";
