<?php
$idioma['titulo_opcao_cadastar'] = 'Cadastrar';
$idioma['titulo_opcao_editar'] = 'Editar';
$idioma['form_erros'] = 'Por favor corrija o(s) erro(s) abaixo: ';
$idioma['modificar_sucesso'] = 'Evento modificado com sucesso.';
$idioma['legendadadosdados'] = 'Dados do evento';
$idioma['form_nome'] = 'Nome:';
$idioma['nome_vazio'] = 'Informe o nome do evento.';
$idioma['nome_utilizado'] = 'O nome informado já está sendo utilizado por outro evento.';
$idioma['form_ativo_painel'] = 'Ativo no painel';
$idioma['ativo_vazio'] = 'Você precisa informar se está ativo ou não.';
$idioma['form_ativo_ajuda'] = 'Essa funcionalidade não remove do painel, somente oculta em relacionamentos com outras funcionalidades';
$idioma['form_mensalidade'] = 'Mensalidade:';
$idioma['mensalidade_vazio'] = 'Você precisa informar se esse evento é de mensalidade ou não.';
$idioma['form_mensalidade_ajuda'] = '';
$idioma['form_taxa_reativacao'] = 'Taxa de Reativacao:';
$idioma['taxa_reativacao_vazio'] = 'Você precisa informar se esse evento é de taxa de reativação ou não.';
$idioma['evento_mensalidade_duplicada'] = 'Já existe um evento financeiro de mensalidade cadastrado e apenas um evento financeiro pode ser de mensalidade.';
$idioma['evento_taxa_reativacao_duplicado'] = 'Já existe um evento financeiro de taxa de reativação cadastrado e apenas um evento financeiro pode ser de taxa de reativação.';
