<?php

$orio_interfaces = array(
    /*
     * ORIO
     */
    1 => array(
        'slug' => 'matricula',
        'tipo' => 'E',
        'nome' => 'Matrícula',
        'protocolo' => 'REST',
        'descricao' => 'Cadastrar matrícula',
    ),
    2 => array(
        'slug' => 'matricula_cfc',
        'tipo' => 'E',
        'nome' => 'Matrícula (CFC)',
        'protocolo' => 'REST',
        'descricao' => 'Cadastrar matrícula por CFC',
    ),
    3 => array(
        'slug' => 'pagarme_criar_boleto',
        'tipo' => 'S',
        'nome' => 'Pagar.me Boleto',
        'protocolo' => 'REST',
        'descricao' => 'Criar novo boleto',
    ),
    4 => array(
        'slug' => 'pagarme_criar_transacao',
        'tipo' => 'S',
        'nome' => 'Pagar.me Transação',
        'protocolo' => 'REST',
        'descricao' => 'Criar nova transação',
    ),
    5 => array(
        'slug' => 'detran_es_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran ES - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN ES',
    ),
    6 => array(
        'slug' => 'detran_al_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran AL - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN AL',
    ),
    7 => array(
        'slug' => 'detran_ms_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran MS - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN MS',
    ),
    8 => array(
        'slug' => 'detran_mt_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran MT - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN MT',
    ),
    9 => array(
        'slug' => 'detran_pe_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran PE - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN PE',
    ),
    10 => array(
        'slug' => 'detran_pr_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran PR - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN PR',
    ),
    11 => array(
        'slug' => 'detran_rj_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran RJ - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN RJ',
    ),
    12 => array(
        'slug' => 'detran_rs_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran RS - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN RS',
    ),
    13 => array(
        'slug' => 'detran_se_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran SE - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN SE',
    ),
    14 => array(
        'slug' => 'detran_al_certificado',
        'tipo' => 'S',
        'nome' => 'Detran AL - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN AL',
    ),
    15 => array(
        'slug' => 'detran_es_certificado',
        'tipo' => 'S',
        'nome' => 'Detran ES - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN ES',
    ),
    16 => array(
        'slug' => 'detran_ma_certificado',
        'tipo' => 'S',
        'nome' => 'Detran MA - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN MA',
    ),
    17 => array(
        'slug' => 'detran_ms_certificado',
        'tipo' => 'S',
        'nome' => 'Detran MS - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN MS',
    ),
    18 => array(
        'slug' => 'detran_mt_certificado',
        'tipo' => 'S',
        'nome' => 'Detran MT - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN MT',
    ),
    19 => array(
        'slug' => 'detran_pe_certificado',
        'tipo' => 'S',
        'nome' => 'Detran PE - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN PE',
    ),
    20 => array(
        'slug' => 'detran_pr_certificado',
        'tipo' => 'S',
        'nome' => 'Detran PR - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN PR',
    ),
    21 => array(
        'slug' => 'detran_rj_certificado',
        'tipo' => 'S',
        'nome' => 'Detran RJ - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN RJ',
    ),
    22 => array(
        'slug' => 'detran_rs_certificado',
        'tipo' => 'S',
        'nome' => 'Detran RS - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN RS',
    ),
    23 => array(
        'slug' => 'detran_se_certificado',
        'tipo' => 'S',
        'nome' => 'Detran SE - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN SE',
    ),
    24 => array(
        'slug' => 'detran_pe_creditos',
        'tipo' => 'S',
        'nome' => 'Detran PE - Creditos',
        'protocolo' => 'REST',
        'descricao' => 'Creditos do DETRAN PE',
    ),
    25 => array(
        'slug' => 'detran_se_creditos',
        'tipo' => 'S',
        'nome' => 'Detran SE - Creditos',
        'protocolo' => 'REST',
        'descricao' => 'Creditos do DETRAN SE',
    ),
    26 => array(
        'slug' => 'detran_pe_cancelamento',
        'tipo' => 'S',
        'nome' => 'Detran PE - Cancelamento',
        'protocolo' => 'REST',
        'descricao' => 'Cancelamento do DETRAN PE',
    ),
    27 => array(
        'slug' => 'detran_pe_importacao',
        'tipo' => 'S',
        'nome' => 'Detran PE - Importação',
        'protocolo' => 'REST',
        'descricao' => 'Importação para DETRAN PE',
    ),
    28 => array(
        'slug' => 'detran_sc_liberacao',
        'tipo' => 'S',
        'nome' => 'Detran SC - Liberação',
        'protocolo' => 'REST',
        'descricao' => 'Liberação do DETRAN SC',
    ),
    29 => array(
        'slug' => 'detran_sc_certificado',
        'tipo' => 'S',
        'nome' => 'Detran SC - Certificado',
        'protocolo' => 'REST',
        'descricao' => 'Certificado do DETRAN SC',
    ),
);
