<?php
$idioma["titulo_opcao_cadastar"] = "Cadastrar";
$idioma["titulo_opcao_editar"] = "Editar";
$idioma["form_erros"] = "Por favor corrija o(s) erro(s) abaixo: ";
$idioma["modificar_sucesso"] = "Tipo de documento modificado com sucesso.";
$idioma["legendadadosdados"] = "Dados do tipo de documento";
$idioma["form_nome"] = "Nome";
$idioma["nome_vazio"] = "Informe o nome do tipo de documento.";
$idioma["nome_utilizado"] = "O nome informado já está sendo utilizado por outro tipo de documento.";
$idioma["form_ativo_painel"] = "Ativo no painel";
$idioma["ativo_vazio"] = "Você precisa informar se está ativo ou não.";
$idioma["form_ativo_ajuda"] = "Essa funcionalidade não remove do painel, somente oculta em relacionamentos com outras funcionalidades";
$idioma["form_exibir_ava"] = "Exibir no Ava";
$idioma["exibir_ava_vazio"] = "Você precisa informar o campo exibir no ava.";
$idioma["form_exibir_ava_ajuda"] = "Indica se será exibido no AVA para o aluno";
$idioma["form_obrigatorio_workflow"] = "Obrigatório:";
$idioma["obrigatorio_workflow_vazio"] = "Informe se o Tipo será obrigatório no workflow.";
$idioma["form_documento_foto"] = "Doc. com foto oficial";
$idioma["documento_vazio"] = "Você precisa informar se esse documento é com foto oficial ou não.";
